name: Main Pipeline

on:
  push:
    branches: [main]

jobs:
  # 1️⃣ Build & Test
  build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      python_version: 3.12

  # 2️⃣ Docker Build & Push
  docker:
    needs: build-test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: khirappawar1/capstone-app
      tag: latest
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  # 3️⃣ Security Scan (Trivy)
  security-scan:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy Scan (Fail on CRITICAL)
        run: |
          trivy image \
          --severity CRITICAL \
          --exit-code 1 \
          --ignore-unfixed \
          --format table \
          --output trivy-report.txt \
          khirappawar1/capstone-app:latest

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
            name: trivy-report
            path: trivy-report.txt

  # 4️⃣ Deploy
  deploy:
    needs: security-scan   # ✅ FIXED
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy
        run: |
          echo "Deploying image: khirappawar1/capstone-app:latest to production"